name: paka
description: Resource Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  is_first_run: ^1.0.0
  line_awesome_flutter: ^2.0.0
  nigerian_states_and_lga: ^1.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/images/paka_logo.png"
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
